/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qhuzfeizljimreovqgqr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFodXpmZWl6bGppbXJlb3ZxZ3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxNzY2MjIsImV4cCI6MjA4OTc1MjYyMn0.SiBktWdrX2tmBbCpyznjdycCpCl-7UYzaksCpYEUK-E"