/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wcjenjebetvwkxnptvib"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjamVuamViZXR2d2t4bnB0dmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5Njc0NDIsImV4cCI6MjA4OTU0MzQ0Mn0.UJxzI3OUVAJY-SxMU7QQ-DVySFd2fwRj1xqDUlMJIYM"